name: Renovate
on:
  push:
    branches: ['main']
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 4 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: renovatebot/github-action@v32.0.1
        with:
          configurationFile: .renovaterc.js
          token: ${{ secrets.GITHUB_TOKEN }}
